### ISSUE TITLE
[BUG] Content in patternfly.css does not load properly

### ISSUE THREAD

**Issue by heartbreaker0** [45Drives/cockpit-samba-manager#2]
Hello, I'm a user of Ubuntu20.04.02 and installed Cockpit and cockpit-samba-manager plugin. When i opened the "Samba" page it seems like that the webpage does not load properly. I checked the console of Firefox and find an Error says that : "Resources have been stop from "https://localhost:9090/src/base1/patternfly.css", because the MIME Type (" text/HTML ") does not match (X - the content-type - Options: Nosniff)."

![2](https://user-images.githubusercontent.com/48881427/119295120-9e291a00-bc88-11eb-906c-3a600907e427.png)

No matter whether the problem can be solved or not, thank you very much.

**Comment by kkesoteco** [comment]
Same Issue.

The error in console is - 
The resource from “https://XX.XX.XX.XX:9090/src/base1/patternfly.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

**Comment by Onyx1640** [comment]
Same issue. Fresh Ubuntu 20.04 install.

**Comment by sam55silver** [comment]
Hello everyone, cockpit-file-manager has been moved under the cockpit-file-sharing project found here: [https://github.com/45Drives/cockpit-file-sharing](url) installing this new package will fix this issue.
